# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
#pod 'Google/Analytics'

target 'GameRyukNew' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GameRyuk
    pod 'YYCache'
    pod 'YYModel' 
    pod 'YYKit'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'MJExtension'
end
