<?php
$CONF = array();

$CONF['wow'] = array(
		0 => array(
			"game" => 'wow',
			"platform" => 'Efun',
			"server" => 'Efun_dev_all',
			"ip" => '203.90.234.115',
			'script_port' => 5143,
		),
		1 => array(
			"game" => 'wow',
			"platform" => 'Efun',
			"server" => 'Efun_online_all',
			"ip" => '103.227.130.72',
			'script_port' => 5132,
		),
		2 => array(
			"game" => 'wow',
			"platform" => 'Efun',
			"server" => 'Efun_test_all',
			"ip" => '123.59.58.83',
			'script_port' => 5132,
		),
		3 => array(
			"game" => 'wow',
			"platform" => 'Efun',
			"server" => 'Efun_shen_ios',
			"ip" => '203.69.109.58',
			'script_port' => 5132,
		),
		4 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_dev_all',
				"ip" => '125.209.194.35',
				'script_port' => 5132,
		),
		5 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_online_all',
				"ip" => '125.209.198.38',
				'script_port' => 5132,
		),
/*		6 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_shen_ios',
				"ip" => '1.255.56.62',
				'script_port' => 5132,
		),
*/		7 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_test_all',
				"ip" => '125.209.198.38',
				'script_port' => 5142,
		),
		8 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_test_android',
				"ip" => '23.91.98.206',
				'script_port' => 5132,
		),
		9 => array(
				"game" => 'wow',
				"platform" => 'Entermate',
				"server" => 'Entermate_test_ios ',
				"ip" => '23.91.98.206',
				'script_port' => 5132,
		),
		10 => array(
				"game" => 'wow',
				"platform" => 'gNetop',
				"server" => 'gNetop_dev_all ',
				"ip" => '203.90.234.115',
				'script_port' => 5153,
		),
		11 => array(
				"game" => 'wow',
				"platform" => 'gNetop',
				"server" => 'gNetop_online_all ',
				"ip" => '23.91.98.147',
				'script_port' => 5132,
		),
		12 => array(
				"game" => 'wow',
				"platform" => 'gNetop',
				"server" => 'gNetop_test_android ',
				"ip" => '23.91.98.205',
				'script_port' => 5132,
		),
		13 => array(
				"game" => 'wow',
				"platform" => 'gNetop',
				"server" => 'gNetop_test_ios ',
				"ip" => '23.91.98.205',
				'script_port' => 5132,
		),
		14 => array(
				"game" => 'wow',
				"platform" => 'gNetop',
				"server" => 'gNetop_shen_ios ',
				"ip" => '54.92.50.176',
				'script_port' => 5132,
		),
		15 => array(
				"game" => 'wow',
				"platform" => 'R2',
				"server" => 'R2_dev_all ',
				"ip" => '203.90.234.115',
				'script_port' => 5142,
		),
		16 => array(
				"game" => 'wow',
				"platform" => 'R2',
				"server" => 'R2_online_all ',
				"ip" => '54.173.233.19',
				'script_port' => 5132,
		),
		17 => array(
				"game" => 'wow',
				"platform" => 'R2',
				"server" => 'R2_shen_ios ',
				"ip" => '54.88.76.207',
				'script_port' => 5132,
		),
		18 => array(
				"game" => 'wow',
				"platform" => 'R2',
				"server" => 'R2_test_all ',
				"ip" => '123.59.58.84',
				'script_port' => 5132,
		),
);
