local function a(str) str = string.gsub(str,"%<","[") str = string.gsub(str,"%>","]") return str end 
local SaveChatRecordIdList = {
getChatPlayerIdList17={},
getChatPlayerIdList12={},
getChatPlayerIdList1132={},
getChatPlayerIdList4={},
getChatPlayerIdList482={},
getChatPlayerIdList2={},
getChatPlayerIdList13={},
getChatPlayerIdList7={},
getChatPlayerIdList295={},
getChatPlayerIdList113={},
getChatPlayerIdList1326={},
getChatPlayerIdList586={},
getChatPlayerIdList3={},
getChatPlayerIdList8={},
getChatPlayerIdList73={},
getChatPlayerIdList151={},
getChatPlayerIdList123={},
getChatPlayerIdList118={},
getChatPlayerIdList128={},
getChatPlayerIdList86={},
getChatPlayerIdList15={},
}
return SaveChatRecordIdList