// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BadgeOpr.proto

package com.guaji.game.protocol;

public final class BadgeOpr {
  private BadgeOpr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HPBadgeDressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 badgeId = 1;
    /**
     * <code>required int64 badgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    boolean hasBadgeId();
    /**
     * <code>required int64 badgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    long getBadgeId();

    // required int32 roleId = 2;
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    boolean hasRoleId();
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    int getRoleId();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *1 表示穿上 2 表示卸下
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *1 表示穿上 2 表示卸下
     * </pre>
     */
    int getType();
  }
  /**
   * Protobuf type {@code HPBadgeDress}
   *
   * <pre>
   *角色穿徽章
   * </pre>
   */
  public static final class HPBadgeDress extends
      com.google.protobuf.GeneratedMessage
      implements HPBadgeDressOrBuilder {
    // Use HPBadgeDress.newBuilder() to construct.
    private HPBadgeDress(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPBadgeDress(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPBadgeDress defaultInstance;
    public static HPBadgeDress getDefaultInstance() {
      return defaultInstance;
    }

    public HPBadgeDress getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPBadgeDress(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              badgeId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roleId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDress_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.BadgeOpr.HPBadgeDress.class, com.guaji.game.protocol.BadgeOpr.HPBadgeDress.Builder.class);
    }

    public static com.google.protobuf.Parser<HPBadgeDress> PARSER =
        new com.google.protobuf.AbstractParser<HPBadgeDress>() {
      public HPBadgeDress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPBadgeDress(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPBadgeDress> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 badgeId = 1;
    public static final int BADGEID_FIELD_NUMBER = 1;
    private long badgeId_;
    /**
     * <code>required int64 badgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    public boolean hasBadgeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 badgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    public long getBadgeId() {
      return badgeId_;
    }

    // required int32 roleId = 2;
    public static final int ROLEID_FIELD_NUMBER = 2;
    private int roleId_;
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    public int getRoleId() {
      return roleId_;
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *1 表示穿上 2 表示卸下
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *1 表示穿上 2 表示卸下
     * </pre>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      badgeId_ = 0L;
      roleId_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBadgeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, badgeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, roleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, badgeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.BadgeOpr.HPBadgeDress prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPBadgeDress}
     *
     * <pre>
     *角色穿徽章
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.BadgeOpr.HPBadgeDressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDress_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.BadgeOpr.HPBadgeDress.class, com.guaji.game.protocol.BadgeOpr.HPBadgeDress.Builder.class);
      }

      // Construct using com.guaji.game.protocol.BadgeOpr.HPBadgeDress.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        badgeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDress_descriptor;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDress getDefaultInstanceForType() {
        return com.guaji.game.protocol.BadgeOpr.HPBadgeDress.getDefaultInstance();
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDress build() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDress buildPartial() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDress result = new com.guaji.game.protocol.BadgeOpr.HPBadgeDress(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.badgeId_ = badgeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.BadgeOpr.HPBadgeDress) {
          return mergeFrom((com.guaji.game.protocol.BadgeOpr.HPBadgeDress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.BadgeOpr.HPBadgeDress other) {
        if (other == com.guaji.game.protocol.BadgeOpr.HPBadgeDress.getDefaultInstance()) return this;
        if (other.hasBadgeId()) {
          setBadgeId(other.getBadgeId());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBadgeId()) {
          
          return false;
        }
        if (!hasRoleId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDress parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.BadgeOpr.HPBadgeDress) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 badgeId = 1;
      private long badgeId_ ;
      /**
       * <code>required int64 badgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public boolean hasBadgeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public long getBadgeId() {
        return badgeId_;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public Builder setBadgeId(long value) {
        bitField0_ |= 0x00000001;
        badgeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public Builder clearBadgeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        badgeId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 roleId = 2;
      private int roleId_ ;
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public int getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public Builder setRoleId(int value) {
        bitField0_ |= 0x00000002;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = 0;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *1 表示穿上 2 表示卸下
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *1 表示穿上 2 表示卸下
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *1 表示穿上 2 表示卸下
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *1 表示穿上 2 表示卸下
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPBadgeDress)
    }

    static {
      defaultInstance = new HPBadgeDress(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPBadgeDress)
  }

  public interface HPBadgeDressRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 onBadgeId = 1;
    /**
     * <code>optional int64 onBadgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    boolean hasOnBadgeId();
    /**
     * <code>optional int64 onBadgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    long getOnBadgeId();

    // required int32 roleId = 2;
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    boolean hasRoleId();
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    int getRoleId();

    // optional int64 offBadgeId = 3;
    /**
     * <code>optional int64 offBadgeId = 3;</code>
     *
     * <pre>
     * 卸下的徽章
     * </pre>
     */
    boolean hasOffBadgeId();
    /**
     * <code>optional int64 offBadgeId = 3;</code>
     *
     * <pre>
     * 卸下的徽章
     * </pre>
     */
    long getOffBadgeId();
  }
  /**
   * Protobuf type {@code HPBadgeDressRet}
   */
  public static final class HPBadgeDressRet extends
      com.google.protobuf.GeneratedMessage
      implements HPBadgeDressRetOrBuilder {
    // Use HPBadgeDressRet.newBuilder() to construct.
    private HPBadgeDressRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPBadgeDressRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPBadgeDressRet defaultInstance;
    public static HPBadgeDressRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPBadgeDressRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPBadgeDressRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              onBadgeId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roleId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              offBadgeId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDressRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDressRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.class, com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPBadgeDressRet> PARSER =
        new com.google.protobuf.AbstractParser<HPBadgeDressRet>() {
      public HPBadgeDressRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPBadgeDressRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPBadgeDressRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 onBadgeId = 1;
    public static final int ONBADGEID_FIELD_NUMBER = 1;
    private long onBadgeId_;
    /**
     * <code>optional int64 onBadgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    public boolean hasOnBadgeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 onBadgeId = 1;</code>
     *
     * <pre>
     *徽章ID
     * </pre>
     */
    public long getOnBadgeId() {
      return onBadgeId_;
    }

    // required int32 roleId = 2;
    public static final int ROLEID_FIELD_NUMBER = 2;
    private int roleId_;
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 roleId = 2;</code>
     *
     * <pre>
     *角色Id
     * </pre>
     */
    public int getRoleId() {
      return roleId_;
    }

    // optional int64 offBadgeId = 3;
    public static final int OFFBADGEID_FIELD_NUMBER = 3;
    private long offBadgeId_;
    /**
     * <code>optional int64 offBadgeId = 3;</code>
     *
     * <pre>
     * 卸下的徽章
     * </pre>
     */
    public boolean hasOffBadgeId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 offBadgeId = 3;</code>
     *
     * <pre>
     * 卸下的徽章
     * </pre>
     */
    public long getOffBadgeId() {
      return offBadgeId_;
    }

    private void initFields() {
      onBadgeId_ = 0L;
      roleId_ = 0;
      offBadgeId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, onBadgeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, roleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, offBadgeId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, onBadgeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roleId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, offBadgeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPBadgeDressRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.BadgeOpr.HPBadgeDressRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDressRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDressRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.class, com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        onBadgeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        roleId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        offBadgeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeDressRet_descriptor;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet build() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet buildPartial() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet result = new com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.onBadgeId_ = onBadgeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roleId_ = roleId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.offBadgeId_ = offBadgeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet) {
          return mergeFrom((com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet other) {
        if (other == com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet.getDefaultInstance()) return this;
        if (other.hasOnBadgeId()) {
          setOnBadgeId(other.getOnBadgeId());
        }
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasOffBadgeId()) {
          setOffBadgeId(other.getOffBadgeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.BadgeOpr.HPBadgeDressRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 onBadgeId = 1;
      private long onBadgeId_ ;
      /**
       * <code>optional int64 onBadgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public boolean hasOnBadgeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 onBadgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public long getOnBadgeId() {
        return onBadgeId_;
      }
      /**
       * <code>optional int64 onBadgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public Builder setOnBadgeId(long value) {
        bitField0_ |= 0x00000001;
        onBadgeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 onBadgeId = 1;</code>
       *
       * <pre>
       *徽章ID
       * </pre>
       */
      public Builder clearOnBadgeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        onBadgeId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 roleId = 2;
      private int roleId_ ;
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public int getRoleId() {
        return roleId_;
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public Builder setRoleId(int value) {
        bitField0_ |= 0x00000002;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 roleId = 2;</code>
       *
       * <pre>
       *角色Id
       * </pre>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 offBadgeId = 3;
      private long offBadgeId_ ;
      /**
       * <code>optional int64 offBadgeId = 3;</code>
       *
       * <pre>
       * 卸下的徽章
       * </pre>
       */
      public boolean hasOffBadgeId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 offBadgeId = 3;</code>
       *
       * <pre>
       * 卸下的徽章
       * </pre>
       */
      public long getOffBadgeId() {
        return offBadgeId_;
      }
      /**
       * <code>optional int64 offBadgeId = 3;</code>
       *
       * <pre>
       * 卸下的徽章
       * </pre>
       */
      public Builder setOffBadgeId(long value) {
        bitField0_ |= 0x00000004;
        offBadgeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 offBadgeId = 3;</code>
       *
       * <pre>
       * 卸下的徽章
       * </pre>
       */
      public Builder clearOffBadgeId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        offBadgeId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPBadgeDressRet)
    }

    static {
      defaultInstance = new HPBadgeDressRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPBadgeDressRet)
  }

  public interface HPBadgeUpgradeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 badgeId = 1;
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    boolean hasBadgeId();
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    long getBadgeId();

    // repeated int64 swallowedBadgeId = 2;
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    java.util.List<java.lang.Long> getSwallowedBadgeIdList();
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    int getSwallowedBadgeIdCount();
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    long getSwallowedBadgeId(int index);
  }
  /**
   * Protobuf type {@code HPBadgeUpgrade}
   *
   * <pre>
   *徽章吞噬
   * </pre>
   */
  public static final class HPBadgeUpgrade extends
      com.google.protobuf.GeneratedMessage
      implements HPBadgeUpgradeOrBuilder {
    // Use HPBadgeUpgrade.newBuilder() to construct.
    private HPBadgeUpgrade(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPBadgeUpgrade(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPBadgeUpgrade defaultInstance;
    public static HPBadgeUpgrade getDefaultInstance() {
      return defaultInstance;
    }

    public HPBadgeUpgrade getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPBadgeUpgrade(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              badgeId_ = input.readInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                swallowedBadgeId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              swallowedBadgeId_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                swallowedBadgeId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                swallowedBadgeId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          swallowedBadgeId_ = java.util.Collections.unmodifiableList(swallowedBadgeId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeUpgrade_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeUpgrade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.class, com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.Builder.class);
    }

    public static com.google.protobuf.Parser<HPBadgeUpgrade> PARSER =
        new com.google.protobuf.AbstractParser<HPBadgeUpgrade>() {
      public HPBadgeUpgrade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPBadgeUpgrade(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPBadgeUpgrade> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 badgeId = 1;
    public static final int BADGEID_FIELD_NUMBER = 1;
    private long badgeId_;
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    public boolean hasBadgeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    public long getBadgeId() {
      return badgeId_;
    }

    // repeated int64 swallowedBadgeId = 2;
    public static final int SWALLOWEDBADGEID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> swallowedBadgeId_;
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getSwallowedBadgeIdList() {
      return swallowedBadgeId_;
    }
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    public int getSwallowedBadgeIdCount() {
      return swallowedBadgeId_.size();
    }
    /**
     * <code>repeated int64 swallowedBadgeId = 2;</code>
     *
     * <pre>
     *被吞噬的徽章
     * </pre>
     */
    public long getSwallowedBadgeId(int index) {
      return swallowedBadgeId_.get(index);
    }

    private void initFields() {
      badgeId_ = 0L;
      swallowedBadgeId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBadgeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, badgeId_);
      }
      for (int i = 0; i < swallowedBadgeId_.size(); i++) {
        output.writeInt64(2, swallowedBadgeId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, badgeId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < swallowedBadgeId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(swallowedBadgeId_.get(i));
        }
        size += dataSize;
        size += 1 * getSwallowedBadgeIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPBadgeUpgrade}
     *
     * <pre>
     *徽章吞噬
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.BadgeOpr.HPBadgeUpgradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeUpgrade_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeUpgrade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.class, com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.Builder.class);
      }

      // Construct using com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        badgeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        swallowedBadgeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPBadgeUpgrade_descriptor;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade getDefaultInstanceForType() {
        return com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.getDefaultInstance();
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade build() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade buildPartial() {
        com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade result = new com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.badgeId_ = badgeId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          swallowedBadgeId_ = java.util.Collections.unmodifiableList(swallowedBadgeId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.swallowedBadgeId_ = swallowedBadgeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade) {
          return mergeFrom((com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade other) {
        if (other == com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade.getDefaultInstance()) return this;
        if (other.hasBadgeId()) {
          setBadgeId(other.getBadgeId());
        }
        if (!other.swallowedBadgeId_.isEmpty()) {
          if (swallowedBadgeId_.isEmpty()) {
            swallowedBadgeId_ = other.swallowedBadgeId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSwallowedBadgeIdIsMutable();
            swallowedBadgeId_.addAll(other.swallowedBadgeId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBadgeId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.BadgeOpr.HPBadgeUpgrade) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 badgeId = 1;
      private long badgeId_ ;
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public boolean hasBadgeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public long getBadgeId() {
        return badgeId_;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public Builder setBadgeId(long value) {
        bitField0_ |= 0x00000001;
        badgeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public Builder clearBadgeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        badgeId_ = 0L;
        onChanged();
        return this;
      }

      // repeated int64 swallowedBadgeId = 2;
      private java.util.List<java.lang.Long> swallowedBadgeId_ = java.util.Collections.emptyList();
      private void ensureSwallowedBadgeIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          swallowedBadgeId_ = new java.util.ArrayList<java.lang.Long>(swallowedBadgeId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getSwallowedBadgeIdList() {
        return java.util.Collections.unmodifiableList(swallowedBadgeId_);
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public int getSwallowedBadgeIdCount() {
        return swallowedBadgeId_.size();
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public long getSwallowedBadgeId(int index) {
        return swallowedBadgeId_.get(index);
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public Builder setSwallowedBadgeId(
          int index, long value) {
        ensureSwallowedBadgeIdIsMutable();
        swallowedBadgeId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public Builder addSwallowedBadgeId(long value) {
        ensureSwallowedBadgeIdIsMutable();
        swallowedBadgeId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public Builder addAllSwallowedBadgeId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSwallowedBadgeIdIsMutable();
        super.addAll(values, swallowedBadgeId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 swallowedBadgeId = 2;</code>
       *
       * <pre>
       *被吞噬的徽章
       * </pre>
       */
      public Builder clearSwallowedBadgeId() {
        swallowedBadgeId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPBadgeUpgrade)
    }

    static {
      defaultInstance = new HPBadgeUpgrade(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPBadgeUpgrade)
  }

  public interface HPEquipUpgradeRetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 badgeId = 1;
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    boolean hasBadgeId();
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    long getBadgeId();
  }
  /**
   * Protobuf type {@code HPEquipUpgradeRet}
   */
  public static final class HPEquipUpgradeRet extends
      com.google.protobuf.GeneratedMessage
      implements HPEquipUpgradeRetOrBuilder {
    // Use HPEquipUpgradeRet.newBuilder() to construct.
    private HPEquipUpgradeRet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HPEquipUpgradeRet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HPEquipUpgradeRet defaultInstance;
    public static HPEquipUpgradeRet getDefaultInstance() {
      return defaultInstance;
    }

    public HPEquipUpgradeRet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HPEquipUpgradeRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              badgeId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPEquipUpgradeRet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guaji.game.protocol.BadgeOpr.internal_static_HPEquipUpgradeRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.class, com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.Builder.class);
    }

    public static com.google.protobuf.Parser<HPEquipUpgradeRet> PARSER =
        new com.google.protobuf.AbstractParser<HPEquipUpgradeRet>() {
      public HPEquipUpgradeRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HPEquipUpgradeRet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HPEquipUpgradeRet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 badgeId = 1;
    public static final int BADGEID_FIELD_NUMBER = 1;
    private long badgeId_;
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    public boolean hasBadgeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 badgeId = 1;</code>
     */
    public long getBadgeId() {
      return badgeId_;
    }

    private void initFields() {
      badgeId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBadgeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, badgeId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, badgeId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HPEquipUpgradeRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPEquipUpgradeRet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPEquipUpgradeRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.class, com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.Builder.class);
      }

      // Construct using com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        badgeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guaji.game.protocol.BadgeOpr.internal_static_HPEquipUpgradeRet_descriptor;
      }

      public com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet getDefaultInstanceForType() {
        return com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.getDefaultInstance();
      }

      public com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet build() {
        com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet buildPartial() {
        com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet result = new com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.badgeId_ = badgeId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet) {
          return mergeFrom((com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet other) {
        if (other == com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet.getDefaultInstance()) return this;
        if (other.hasBadgeId()) {
          setBadgeId(other.getBadgeId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBadgeId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guaji.game.protocol.BadgeOpr.HPEquipUpgradeRet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 badgeId = 1;
      private long badgeId_ ;
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public boolean hasBadgeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public long getBadgeId() {
        return badgeId_;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public Builder setBadgeId(long value) {
        bitField0_ |= 0x00000001;
        badgeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 badgeId = 1;</code>
       */
      public Builder clearBadgeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        badgeId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HPEquipUpgradeRet)
    }

    static {
      defaultInstance = new HPEquipUpgradeRet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HPEquipUpgradeRet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPBadgeDress_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPBadgeDress_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPBadgeDressRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPBadgeDressRet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPBadgeUpgrade_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPBadgeUpgrade_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HPEquipUpgradeRet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HPEquipUpgradeRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016BadgeOpr.proto\032\014Reward.proto\032\013Badge.pr" +
      "oto\032\017Attribute.proto\032\013Const.proto\"=\n\014HPB" +
      "adgeDress\022\017\n\007badgeId\030\001 \002(\003\022\016\n\006roleId\030\002 \002" +
      "(\005\022\014\n\004type\030\003 \002(\005\"H\n\017HPBadgeDressRet\022\021\n\to" +
      "nBadgeId\030\001 \001(\003\022\016\n\006roleId\030\002 \002(\005\022\022\n\noffBad" +
      "geId\030\003 \001(\003\";\n\016HPBadgeUpgrade\022\017\n\007badgeId\030" +
      "\001 \002(\003\022\030\n\020swallowedBadgeId\030\002 \003(\003\"$\n\021HPEqu" +
      "ipUpgradeRet\022\017\n\007badgeId\030\001 \002(\003B\031\n\027com.gua" +
      "ji.game.protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HPBadgeDress_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HPBadgeDress_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPBadgeDress_descriptor,
              new java.lang.String[] { "BadgeId", "RoleId", "Type", });
          internal_static_HPBadgeDressRet_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HPBadgeDressRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPBadgeDressRet_descriptor,
              new java.lang.String[] { "OnBadgeId", "RoleId", "OffBadgeId", });
          internal_static_HPBadgeUpgrade_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_HPBadgeUpgrade_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPBadgeUpgrade_descriptor,
              new java.lang.String[] { "BadgeId", "SwallowedBadgeId", });
          internal_static_HPEquipUpgradeRet_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_HPEquipUpgradeRet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HPEquipUpgradeRet_descriptor,
              new java.lang.String[] { "BadgeId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.guaji.game.protocol.Reward.getDescriptor(),
          com.guaji.game.protocol.Badge.getDescriptor(),
          com.guaji.game.protocol.Attribute.getDescriptor(),
          com.guaji.game.protocol.Const.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
