// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Attribute.proto

#ifndef PROTOBUF_Attribute_2eproto__INCLUDED
#define PROTOBUF_Attribute_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Attribute_2eproto();
void protobuf_AssignDesc_Attribute_2eproto();
void protobuf_ShutdownFile_Attribute_2eproto();

class Attr;
class AttrInfo;

// ===================================================================

class Attr : public ::google::protobuf::Message {
 public:
  Attr();
  virtual ~Attr();

  Attr(const Attr& from);

  inline Attr& operator=(const Attr& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Attr& default_instance();

  void Swap(Attr* other);

  // implements Message ----------------------------------------------

  Attr* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Attr& from);
  void MergeFrom(const Attr& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 attrId = 1;
  inline bool has_attrid() const;
  inline void clear_attrid();
  static const int kAttrIdFieldNumber = 1;
  inline ::google::protobuf::int32 attrid() const;
  inline void set_attrid(::google::protobuf::int32 value);

  // required int32 attrValue = 2;
  inline bool has_attrvalue() const;
  inline void clear_attrvalue();
  static const int kAttrValueFieldNumber = 2;
  inline ::google::protobuf::int32 attrvalue() const;
  inline void set_attrvalue(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Attr)
 private:
  inline void set_has_attrid();
  inline void clear_has_attrid();
  inline void set_has_attrvalue();
  inline void clear_has_attrvalue();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 attrid_;
  ::google::protobuf::int32 attrvalue_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Attribute_2eproto();
  friend void protobuf_AssignDesc_Attribute_2eproto();
  friend void protobuf_ShutdownFile_Attribute_2eproto();

  void InitAsDefaultInstance();
  static Attr* default_instance_;
};
// -------------------------------------------------------------------

class AttrInfo : public ::google::protobuf::Message {
 public:
  AttrInfo();
  virtual ~AttrInfo();

  AttrInfo(const AttrInfo& from);

  inline AttrInfo& operator=(const AttrInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AttrInfo& default_instance();

  void Swap(AttrInfo* other);

  // implements Message ----------------------------------------------

  AttrInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AttrInfo& from);
  void MergeFrom(const AttrInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Attr attribute = 1;
  inline int attribute_size() const;
  inline void clear_attribute();
  static const int kAttributeFieldNumber = 1;
  inline const ::Attr& attribute(int index) const;
  inline ::Attr* mutable_attribute(int index);
  inline ::Attr* add_attribute();
  inline const ::google::protobuf::RepeatedPtrField< ::Attr >&
      attribute() const;
  inline ::google::protobuf::RepeatedPtrField< ::Attr >*
      mutable_attribute();

  // @@protoc_insertion_point(class_scope:AttrInfo)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::Attr > attribute_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Attribute_2eproto();
  friend void protobuf_AssignDesc_Attribute_2eproto();
  friend void protobuf_ShutdownFile_Attribute_2eproto();

  void InitAsDefaultInstance();
  static AttrInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// Attr

// required int32 attrId = 1;
inline bool Attr::has_attrid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Attr::set_has_attrid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Attr::clear_has_attrid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Attr::clear_attrid() {
  attrid_ = 0;
  clear_has_attrid();
}
inline ::google::protobuf::int32 Attr::attrid() const {
  return attrid_;
}
inline void Attr::set_attrid(::google::protobuf::int32 value) {
  set_has_attrid();
  attrid_ = value;
}

// required int32 attrValue = 2;
inline bool Attr::has_attrvalue() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Attr::set_has_attrvalue() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Attr::clear_has_attrvalue() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Attr::clear_attrvalue() {
  attrvalue_ = 0;
  clear_has_attrvalue();
}
inline ::google::protobuf::int32 Attr::attrvalue() const {
  return attrvalue_;
}
inline void Attr::set_attrvalue(::google::protobuf::int32 value) {
  set_has_attrvalue();
  attrvalue_ = value;
}

// -------------------------------------------------------------------

// AttrInfo

// repeated .Attr attribute = 1;
inline int AttrInfo::attribute_size() const {
  return attribute_.size();
}
inline void AttrInfo::clear_attribute() {
  attribute_.Clear();
}
inline const ::Attr& AttrInfo::attribute(int index) const {
  return attribute_.Get(index);
}
inline ::Attr* AttrInfo::mutable_attribute(int index) {
  return attribute_.Mutable(index);
}
inline ::Attr* AttrInfo::add_attribute() {
  return attribute_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Attr >&
AttrInfo::attribute() const {
  return attribute_;
}
inline ::google::protobuf::RepeatedPtrField< ::Attr >*
AttrInfo::mutable_attribute() {
  return &attribute_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Attribute_2eproto__INCLUDED
