// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Skill.proto

#ifndef PROTOBUF_Skill_2eproto__INCLUDED
#define PROTOBUF_Skill_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Skill_2eproto();
void protobuf_AssignDesc_Skill_2eproto();
void protobuf_ShutdownFile_Skill_2eproto();

class SkillInfo;
class HPSkillInfoSync;
class HPSkillChangeOrder;
class HPSkillChangeOrderRet;
class HPSkillCarry;
class HPSkillCarryRet;
class HPSkillInfo;

// ===================================================================

class SkillInfo : public ::google::protobuf::Message {
 public:
  SkillInfo();
  virtual ~SkillInfo();

  SkillInfo(const SkillInfo& from);

  inline SkillInfo& operator=(const SkillInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SkillInfo& default_instance();

  void Swap(SkillInfo* other);

  // implements Message ----------------------------------------------

  SkillInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SkillInfo& from);
  void MergeFrom(const SkillInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // required int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 itemId = 3;
  inline bool has_itemid() const;
  inline void clear_itemid();
  static const int kItemIdFieldNumber = 3;
  inline ::google::protobuf::int32 itemid() const;
  inline void set_itemid(::google::protobuf::int32 value);

  // optional int32 skillLevel = 4;
  inline bool has_skilllevel() const;
  inline void clear_skilllevel();
  static const int kSkillLevelFieldNumber = 4;
  inline ::google::protobuf::int32 skilllevel() const;
  inline void set_skilllevel(::google::protobuf::int32 value);

  // optional int32 status = 5;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 5;
  inline ::google::protobuf::int32 status() const;
  inline void set_status(::google::protobuf::int32 value);

  // optional int32 exp = 6;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 6;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:SkillInfo)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_itemid();
  inline void clear_has_itemid();
  inline void set_has_skilllevel();
  inline void clear_has_skilllevel();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_exp();
  inline void clear_has_exp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 skilllevel_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 exp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static SkillInfo* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillInfoSync : public ::google::protobuf::Message {
 public:
  HPSkillInfoSync();
  virtual ~HPSkillInfoSync();

  HPSkillInfoSync(const HPSkillInfoSync& from);

  inline HPSkillInfoSync& operator=(const HPSkillInfoSync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillInfoSync& default_instance();

  void Swap(HPSkillInfoSync* other);

  // implements Message ----------------------------------------------

  HPSkillInfoSync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillInfoSync& from);
  void MergeFrom(const HPSkillInfoSync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .SkillInfo skillInfos = 1;
  inline int skillinfos_size() const;
  inline void clear_skillinfos();
  static const int kSkillInfosFieldNumber = 1;
  inline const ::SkillInfo& skillinfos(int index) const;
  inline ::SkillInfo* mutable_skillinfos(int index);
  inline ::SkillInfo* add_skillinfos();
  inline const ::google::protobuf::RepeatedPtrField< ::SkillInfo >&
      skillinfos() const;
  inline ::google::protobuf::RepeatedPtrField< ::SkillInfo >*
      mutable_skillinfos();

  // @@protoc_insertion_point(class_scope:HPSkillInfoSync)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::SkillInfo > skillinfos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillInfoSync* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillChangeOrder : public ::google::protobuf::Message {
 public:
  HPSkillChangeOrder();
  virtual ~HPSkillChangeOrder();

  HPSkillChangeOrder(const HPSkillChangeOrder& from);

  inline HPSkillChangeOrder& operator=(const HPSkillChangeOrder& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillChangeOrder& default_instance();

  void Swap(HPSkillChangeOrder* other);

  // implements Message ----------------------------------------------

  HPSkillChangeOrder* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillChangeOrder& from);
  void MergeFrom(const HPSkillChangeOrder& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // required int32 skillId = 2;
  inline bool has_skillid() const;
  inline void clear_skillid();
  static const int kSkillIdFieldNumber = 2;
  inline ::google::protobuf::int32 skillid() const;
  inline void set_skillid(::google::protobuf::int32 value);

  // required int32 srcOrder = 3;
  inline bool has_srcorder() const;
  inline void clear_srcorder();
  static const int kSrcOrderFieldNumber = 3;
  inline ::google::protobuf::int32 srcorder() const;
  inline void set_srcorder(::google::protobuf::int32 value);

  // required int32 dstOrder = 4;
  inline bool has_dstorder() const;
  inline void clear_dstorder();
  static const int kDstOrderFieldNumber = 4;
  inline ::google::protobuf::int32 dstorder() const;
  inline void set_dstorder(::google::protobuf::int32 value);

  // required int32 skillBagId = 5;
  inline bool has_skillbagid() const;
  inline void clear_skillbagid();
  static const int kSkillBagIdFieldNumber = 5;
  inline ::google::protobuf::int32 skillbagid() const;
  inline void set_skillbagid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:HPSkillChangeOrder)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_skillid();
  inline void clear_has_skillid();
  inline void set_has_srcorder();
  inline void clear_has_srcorder();
  inline void set_has_dstorder();
  inline void clear_has_dstorder();
  inline void set_has_skillbagid();
  inline void clear_has_skillbagid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 skillid_;
  ::google::protobuf::int32 srcorder_;
  ::google::protobuf::int32 dstorder_;
  ::google::protobuf::int32 skillbagid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillChangeOrder* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillChangeOrderRet : public ::google::protobuf::Message {
 public:
  HPSkillChangeOrderRet();
  virtual ~HPSkillChangeOrderRet();

  HPSkillChangeOrderRet(const HPSkillChangeOrderRet& from);

  inline HPSkillChangeOrderRet& operator=(const HPSkillChangeOrderRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillChangeOrderRet& default_instance();

  void Swap(HPSkillChangeOrderRet* other);

  // implements Message ----------------------------------------------

  HPSkillChangeOrderRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillChangeOrderRet& from);
  void MergeFrom(const HPSkillChangeOrderRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 version = 1 [default = 1];
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:HPSkillChangeOrderRet)
 private:
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 version_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillChangeOrderRet* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillCarry : public ::google::protobuf::Message {
 public:
  HPSkillCarry();
  virtual ~HPSkillCarry();

  HPSkillCarry(const HPSkillCarry& from);

  inline HPSkillCarry& operator=(const HPSkillCarry& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillCarry& default_instance();

  void Swap(HPSkillCarry* other);

  // implements Message ----------------------------------------------

  HPSkillCarry* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillCarry& from);
  void MergeFrom(const HPSkillCarry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // repeated int32 skillId = 2;
  inline int skillid_size() const;
  inline void clear_skillid();
  static const int kSkillIdFieldNumber = 2;
  inline ::google::protobuf::int32 skillid(int index) const;
  inline void set_skillid(int index, ::google::protobuf::int32 value);
  inline void add_skillid(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      skillid() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_skillid();

  // required int32 skillBagId = 3;
  inline bool has_skillbagid() const;
  inline void clear_skillbagid();
  static const int kSkillBagIdFieldNumber = 3;
  inline ::google::protobuf::int32 skillbagid() const;
  inline void set_skillbagid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:HPSkillCarry)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_skillbagid();
  inline void clear_has_skillbagid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > skillid_;
  ::google::protobuf::int32 roleid_;
  ::google::protobuf::int32 skillbagid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillCarry* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillCarryRet : public ::google::protobuf::Message {
 public:
  HPSkillCarryRet();
  virtual ~HPSkillCarryRet();

  HPSkillCarryRet(const HPSkillCarryRet& from);

  inline HPSkillCarryRet& operator=(const HPSkillCarryRet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillCarryRet& default_instance();

  void Swap(HPSkillCarryRet* other);

  // implements Message ----------------------------------------------

  HPSkillCarryRet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillCarryRet& from);
  void MergeFrom(const HPSkillCarryRet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:HPSkillCarryRet)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 roleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillCarryRet* default_instance_;
};
// -------------------------------------------------------------------

class HPSkillInfo : public ::google::protobuf::Message {
 public:
  HPSkillInfo();
  virtual ~HPSkillInfo();

  HPSkillInfo(const HPSkillInfo& from);

  inline HPSkillInfo& operator=(const HPSkillInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HPSkillInfo& default_instance();

  void Swap(HPSkillInfo* other);

  // implements Message ----------------------------------------------

  HPSkillInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HPSkillInfo& from);
  void MergeFrom(const HPSkillInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int32 roleid() const;
  inline void set_roleid(::google::protobuf::int32 value);

  // repeated int32 skillId1 = 2;
  inline int skillid1_size() const;
  inline void clear_skillid1();
  static const int kSkillId1FieldNumber = 2;
  inline ::google::protobuf::int32 skillid1(int index) const;
  inline void set_skillid1(int index, ::google::protobuf::int32 value);
  inline void add_skillid1(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      skillid1() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_skillid1();

  // repeated int32 skillId2 = 3;
  inline int skillid2_size() const;
  inline void clear_skillid2();
  static const int kSkillId2FieldNumber = 3;
  inline ::google::protobuf::int32 skillid2(int index) const;
  inline void set_skillid2(int index, ::google::protobuf::int32 value);
  inline void add_skillid2(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      skillid2() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_skillid2();

  // repeated int32 skillId3 = 4;
  inline int skillid3_size() const;
  inline void clear_skillid3();
  static const int kSkillId3FieldNumber = 4;
  inline ::google::protobuf::int32 skillid3(int index) const;
  inline void set_skillid3(int index, ::google::protobuf::int32 value);
  inline void add_skillid3(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      skillid3() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_skillid3();

  // @@protoc_insertion_point(class_scope:HPSkillInfo)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > skillid1_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > skillid2_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > skillid3_;
  ::google::protobuf::int32 roleid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_Skill_2eproto();
  friend void protobuf_AssignDesc_Skill_2eproto();
  friend void protobuf_ShutdownFile_Skill_2eproto();

  void InitAsDefaultInstance();
  static HPSkillInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// SkillInfo

// required int32 roleId = 1;
inline bool SkillInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SkillInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SkillInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SkillInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 SkillInfo::roleid() const {
  return roleid_;
}
inline void SkillInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// required int32 id = 2;
inline bool SkillInfo::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SkillInfo::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SkillInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SkillInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 SkillInfo::id() const {
  return id_;
}
inline void SkillInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 itemId = 3;
inline bool SkillInfo::has_itemid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SkillInfo::set_has_itemid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SkillInfo::clear_has_itemid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SkillInfo::clear_itemid() {
  itemid_ = 0;
  clear_has_itemid();
}
inline ::google::protobuf::int32 SkillInfo::itemid() const {
  return itemid_;
}
inline void SkillInfo::set_itemid(::google::protobuf::int32 value) {
  set_has_itemid();
  itemid_ = value;
}

// optional int32 skillLevel = 4;
inline bool SkillInfo::has_skilllevel() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SkillInfo::set_has_skilllevel() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SkillInfo::clear_has_skilllevel() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SkillInfo::clear_skilllevel() {
  skilllevel_ = 0;
  clear_has_skilllevel();
}
inline ::google::protobuf::int32 SkillInfo::skilllevel() const {
  return skilllevel_;
}
inline void SkillInfo::set_skilllevel(::google::protobuf::int32 value) {
  set_has_skilllevel();
  skilllevel_ = value;
}

// optional int32 status = 5;
inline bool SkillInfo::has_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SkillInfo::set_has_status() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SkillInfo::clear_has_status() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SkillInfo::clear_status() {
  status_ = 0;
  clear_has_status();
}
inline ::google::protobuf::int32 SkillInfo::status() const {
  return status_;
}
inline void SkillInfo::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
}

// optional int32 exp = 6;
inline bool SkillInfo::has_exp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SkillInfo::set_has_exp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SkillInfo::clear_has_exp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SkillInfo::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 SkillInfo::exp() const {
  return exp_;
}
inline void SkillInfo::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// -------------------------------------------------------------------

// HPSkillInfoSync

// repeated .SkillInfo skillInfos = 1;
inline int HPSkillInfoSync::skillinfos_size() const {
  return skillinfos_.size();
}
inline void HPSkillInfoSync::clear_skillinfos() {
  skillinfos_.Clear();
}
inline const ::SkillInfo& HPSkillInfoSync::skillinfos(int index) const {
  return skillinfos_.Get(index);
}
inline ::SkillInfo* HPSkillInfoSync::mutable_skillinfos(int index) {
  return skillinfos_.Mutable(index);
}
inline ::SkillInfo* HPSkillInfoSync::add_skillinfos() {
  return skillinfos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::SkillInfo >&
HPSkillInfoSync::skillinfos() const {
  return skillinfos_;
}
inline ::google::protobuf::RepeatedPtrField< ::SkillInfo >*
HPSkillInfoSync::mutable_skillinfos() {
  return &skillinfos_;
}

// -------------------------------------------------------------------

// HPSkillChangeOrder

// required int32 roleId = 1;
inline bool HPSkillChangeOrder::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HPSkillChangeOrder::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HPSkillChangeOrder::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HPSkillChangeOrder::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 HPSkillChangeOrder::roleid() const {
  return roleid_;
}
inline void HPSkillChangeOrder::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// required int32 skillId = 2;
inline bool HPSkillChangeOrder::has_skillid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HPSkillChangeOrder::set_has_skillid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HPSkillChangeOrder::clear_has_skillid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HPSkillChangeOrder::clear_skillid() {
  skillid_ = 0;
  clear_has_skillid();
}
inline ::google::protobuf::int32 HPSkillChangeOrder::skillid() const {
  return skillid_;
}
inline void HPSkillChangeOrder::set_skillid(::google::protobuf::int32 value) {
  set_has_skillid();
  skillid_ = value;
}

// required int32 srcOrder = 3;
inline bool HPSkillChangeOrder::has_srcorder() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HPSkillChangeOrder::set_has_srcorder() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HPSkillChangeOrder::clear_has_srcorder() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HPSkillChangeOrder::clear_srcorder() {
  srcorder_ = 0;
  clear_has_srcorder();
}
inline ::google::protobuf::int32 HPSkillChangeOrder::srcorder() const {
  return srcorder_;
}
inline void HPSkillChangeOrder::set_srcorder(::google::protobuf::int32 value) {
  set_has_srcorder();
  srcorder_ = value;
}

// required int32 dstOrder = 4;
inline bool HPSkillChangeOrder::has_dstorder() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HPSkillChangeOrder::set_has_dstorder() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HPSkillChangeOrder::clear_has_dstorder() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HPSkillChangeOrder::clear_dstorder() {
  dstorder_ = 0;
  clear_has_dstorder();
}
inline ::google::protobuf::int32 HPSkillChangeOrder::dstorder() const {
  return dstorder_;
}
inline void HPSkillChangeOrder::set_dstorder(::google::protobuf::int32 value) {
  set_has_dstorder();
  dstorder_ = value;
}

// required int32 skillBagId = 5;
inline bool HPSkillChangeOrder::has_skillbagid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HPSkillChangeOrder::set_has_skillbagid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HPSkillChangeOrder::clear_has_skillbagid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HPSkillChangeOrder::clear_skillbagid() {
  skillbagid_ = 0;
  clear_has_skillbagid();
}
inline ::google::protobuf::int32 HPSkillChangeOrder::skillbagid() const {
  return skillbagid_;
}
inline void HPSkillChangeOrder::set_skillbagid(::google::protobuf::int32 value) {
  set_has_skillbagid();
  skillbagid_ = value;
}

// -------------------------------------------------------------------

// HPSkillChangeOrderRet

// optional int32 version = 1 [default = 1];
inline bool HPSkillChangeOrderRet::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HPSkillChangeOrderRet::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HPSkillChangeOrderRet::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HPSkillChangeOrderRet::clear_version() {
  version_ = 1;
  clear_has_version();
}
inline ::google::protobuf::int32 HPSkillChangeOrderRet::version() const {
  return version_;
}
inline void HPSkillChangeOrderRet::set_version(::google::protobuf::int32 value) {
  set_has_version();
  version_ = value;
}

// -------------------------------------------------------------------

// HPSkillCarry

// required int32 roleId = 1;
inline bool HPSkillCarry::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HPSkillCarry::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HPSkillCarry::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HPSkillCarry::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 HPSkillCarry::roleid() const {
  return roleid_;
}
inline void HPSkillCarry::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// repeated int32 skillId = 2;
inline int HPSkillCarry::skillid_size() const {
  return skillid_.size();
}
inline void HPSkillCarry::clear_skillid() {
  skillid_.Clear();
}
inline ::google::protobuf::int32 HPSkillCarry::skillid(int index) const {
  return skillid_.Get(index);
}
inline void HPSkillCarry::set_skillid(int index, ::google::protobuf::int32 value) {
  skillid_.Set(index, value);
}
inline void HPSkillCarry::add_skillid(::google::protobuf::int32 value) {
  skillid_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
HPSkillCarry::skillid() const {
  return skillid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
HPSkillCarry::mutable_skillid() {
  return &skillid_;
}

// required int32 skillBagId = 3;
inline bool HPSkillCarry::has_skillbagid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HPSkillCarry::set_has_skillbagid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HPSkillCarry::clear_has_skillbagid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HPSkillCarry::clear_skillbagid() {
  skillbagid_ = 0;
  clear_has_skillbagid();
}
inline ::google::protobuf::int32 HPSkillCarry::skillbagid() const {
  return skillbagid_;
}
inline void HPSkillCarry::set_skillbagid(::google::protobuf::int32 value) {
  set_has_skillbagid();
  skillbagid_ = value;
}

// -------------------------------------------------------------------

// HPSkillCarryRet

// required int32 roleId = 1;
inline bool HPSkillCarryRet::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HPSkillCarryRet::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HPSkillCarryRet::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HPSkillCarryRet::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 HPSkillCarryRet::roleid() const {
  return roleid_;
}
inline void HPSkillCarryRet::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// -------------------------------------------------------------------

// HPSkillInfo

// required int32 roleId = 1;
inline bool HPSkillInfo::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HPSkillInfo::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HPSkillInfo::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HPSkillInfo::clear_roleid() {
  roleid_ = 0;
  clear_has_roleid();
}
inline ::google::protobuf::int32 HPSkillInfo::roleid() const {
  return roleid_;
}
inline void HPSkillInfo::set_roleid(::google::protobuf::int32 value) {
  set_has_roleid();
  roleid_ = value;
}

// repeated int32 skillId1 = 2;
inline int HPSkillInfo::skillid1_size() const {
  return skillid1_.size();
}
inline void HPSkillInfo::clear_skillid1() {
  skillid1_.Clear();
}
inline ::google::protobuf::int32 HPSkillInfo::skillid1(int index) const {
  return skillid1_.Get(index);
}
inline void HPSkillInfo::set_skillid1(int index, ::google::protobuf::int32 value) {
  skillid1_.Set(index, value);
}
inline void HPSkillInfo::add_skillid1(::google::protobuf::int32 value) {
  skillid1_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
HPSkillInfo::skillid1() const {
  return skillid1_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
HPSkillInfo::mutable_skillid1() {
  return &skillid1_;
}

// repeated int32 skillId2 = 3;
inline int HPSkillInfo::skillid2_size() const {
  return skillid2_.size();
}
inline void HPSkillInfo::clear_skillid2() {
  skillid2_.Clear();
}
inline ::google::protobuf::int32 HPSkillInfo::skillid2(int index) const {
  return skillid2_.Get(index);
}
inline void HPSkillInfo::set_skillid2(int index, ::google::protobuf::int32 value) {
  skillid2_.Set(index, value);
}
inline void HPSkillInfo::add_skillid2(::google::protobuf::int32 value) {
  skillid2_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
HPSkillInfo::skillid2() const {
  return skillid2_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
HPSkillInfo::mutable_skillid2() {
  return &skillid2_;
}

// repeated int32 skillId3 = 4;
inline int HPSkillInfo::skillid3_size() const {
  return skillid3_.size();
}
inline void HPSkillInfo::clear_skillid3() {
  skillid3_.Clear();
}
inline ::google::protobuf::int32 HPSkillInfo::skillid3(int index) const {
  return skillid3_.Get(index);
}
inline void HPSkillInfo::set_skillid3(int index, ::google::protobuf::int32 value) {
  skillid3_.Set(index, value);
}
inline void HPSkillInfo::add_skillid3(::google::protobuf::int32 value) {
  skillid3_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
HPSkillInfo::skillid3() const {
  return skillid3_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
HPSkillInfo::mutable_skillid3() {
  return &skillid3_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Skill_2eproto__INCLUDED
