//
//  MultiLanguageMessage.h
//  ILoveGameSDK
//
//  Created by jung on 2014. 7. 8..
//  Copyright (c) 2014년 Entermate. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface MultiLanguageMessage : NSObject {
    int m_nLoginType;
}

typedef enum {
    MESSAGE_INIT_FAILED_SDK = 1,
    MESSAGE_LOGIN_CANCELLED = 2,
    MESSAGE_CHECK_NETWORK_STATUS = 3,
    MESSAGE_UPDATE_INFO = 4,
    MESSAGE_UPDATE_CONTENT = 5,
    MESSAGE_CONFIRM = 6,
    MESSAGE_CANCEL = 7,
    MESSAGE_TRY_AGAIN = 8,
    MESSAGE_USER_CANCELLED = 9,
    MESSAGE_EVENT = 10,
    MESSAGE_RULE = 11,
    MESSAGE_COMMUNITY = 12,
    MESSAGE_HELP_DESK = 13,
    MESSAGE_TICKET = 14,
    MESSAGE_AGREEMENT = 15,
    MESSAGE_DONTSHOW_DAY = 16,
    MESSAGE_BROWSERACTIVITY_CLOSE = 17,
    MESSAGE_PURCHASE_NO_ITEM = 18,
    MESSAGE_PURCHASE_NO_ITEM_TITLE = 19,
    MESSAGE_ERROR = 20,
    MESSAGE_PURCAHSE_ERROR_CONTENT = 21,
    MESSAGE_GUEST_CONTENT = 22,
    MESSAGE_INVITEMESSAGE = 23,
    MESSAGE_SENDGIFT = 24,
    MESSAGE_PURCHASE_USER_CANCELLED = 25,
    MESSAGE_NOT_ENOUGHDATA = 26,
    MESSAGE_GOTOBACK=27,
    
    MESSAGE_LOGOUT = 100,
    MESSAGE_UNREGISTER = 101,
    MESSAGE_SOCIAL_SENDGIFT = 102,
    MESSAGE_SOCIAL_SENDINVITE = 103,
    MESSAGE_SOCIAL_SENDMESSAGEBLOCK_0 = 104,
    MESSAGE_SOCIAL_SENDMESSAGEBLOCK_1 = 105,
    MESSAGE_SOCIAL_UNREGISTER = 106,
    
}MESSAGE;

-(NSString*) getMessage:(int) nIndex;
-(void) setLoginType:(int)_loginType;
@end
