local MainScenePage_BtnMap = {
    -- LeftScrollview (依 idx 排序)
    {
        key    = "PopUpSale",
        normal = "Lobby_Btn_10.png",
        fun    = "onPoP",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.POPUP_SALE,
        isRed  = false,
        Time   = 0,
        idx    = 1,
    },
    {
        key    = "GloryHole",
        normal = "Lobby_Btn_GloryHole.png",
        fun    = "onGlory",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.GLORY_HOLE,
        isRed  = false,
        Time   = 0,
        idx    = 2,
    },
    {
        key    = "7Day",
        normal = "Lobby_7Days.png",
        fun    = "on7Day",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.SEVENDAY_QUEST,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_SEVENDAY_BTN,
        idx    = 3,
        Time   = 0,
    },
    {
        key    = "IAP",
        normal = "Lobby_Btn_6.png",
        fun    = "onIAP",
        Pos    = "Left",
        Lock   = false,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_PACKAGE_BTN,
        idx    = 4,
    },
    {
        key    = "8Day",
        normal = "Lobby_NewPlayer.png",
        fun    = "onNewPlayer",
        Pos    = "Left",
        Lock   = false,
        isRed  = false,
        idx    = 5,
        Time   = 0,
    },
    {
        key    = "Act_Gift",
        normal = "Lobby_EventShop.png",
        fun    = "onActGift",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.SHOP,
        isRed  = false,
        idx    = 7,
        Time   = 0,
    },
    {
        key    = "Shop",
        normal = "Lobby_Btn_8.png",
        fun    = "onShop",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.SHOP,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_SHOP_BTN,
        idx    = 7,
    },
    {
        key    = "SingleBoss",
        normal = "LobbyBtn_SingleBoss.png",
        fun    = "onSingleBoss",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.SINGLE_BOSS,
        isRed  = false,
        idx    = 8,
        Time   = 0,
    },
    {
        key    = "Star",
        normal = "Lobby_Btn_9.png",
        fun    = "onStar",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.WISHING_WELL,
        isRed  = false,
        idx    = 9,
        Time   = 0,
    },
    {
        key    = "Puzzle",
        normal = "Lobby_Puzzle.png",
        fun    = "onPuzzle",
        Pos    = "Left",
        Lock   = GameConfig.LOCK_PAGE_KEY.PUZZLE,
        isRed  = false,
        idx    = 10,
        Time   = 0,
    },

    -- RightScrollview (依 idx 排序)
    {
        key    = "SecertMsg",
        normal = "Lobby_Btn_11.png",
        fun    = "onSecert",
        Pos    = "Right",
        Lock   = GameConfig.LOCK_PAGE_KEY.SECRET_MESSAGE,
        isRed  = false,
        idx    = 1,
    },
    {
        key    = "Friend",
        normal = "Lobby_Btn_2.png",
        fun    = "onFriend",
        Pos    = "Right",
        Lock   = false,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_FRIEND_BTN,
        idx    = 2,
    },
    {
        key    = "Forge",
        normal = "Lobby_Btn_3.png",
        fun    = "onForge",
        Pos    = "Right",
        Lock   = GameConfig.LOCK_PAGE_KEY.FORGE,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_FORGE_BTN,
        idx    = 3,
    },
    {
        key    = "Expdtion",
        normal = "Lobby_Btn_4.png",
        fun    = "onBounty",
        Pos    = "Right",
        Lock   = GameConfig.LOCK_PAGE_KEY.BOUNTY,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_BOUNTY_BTN,
        idx    = 4,
    },
    {
        key    = "Quest",
        normal = "Lobby_Btn_1.png",
        fun    = "onQuest",
        Pos    = "Right",
        Lock   = GameConfig.LOCK_PAGE_KEY.QUEST,
        isRed  = RedPointManager.PAGE_IDS.LOBBY_QUEST_BTN,
        idx    = 5,
    },
    {
        key    = "Reward",
        normal = "Lobby_Btn_7.png",
        fun    = "onReward",
        Pos    = "Right",
        Lock   = GameConfig.LOCK_PAGE_KEY.SUMMON_900,
        isRed  = false,
        idx    = 6,
    },
}

return MainScenePage_BtnMap
